### ISSUE TITLE
How to use lua standard libraries with alominum lua

### ISSUE THREAD

**Issue by mohas** [chkn/AluminumLua#7]
Hi
How can I use lua's standard library functions with aluminumlua? should I write library extensions like AddBasicLibrary() function?

**Comment by chkn** [comment]
There is only basic support for a couple APIs from the lua standard libraries here: https://github.com/chkn/AluminumLua/tree/master/src/Libraries

You could implement additional functions in C# following the same pattern. Library functions should also have tests.

**Comment by mohas** [comment]
OK, thanks for reply and wonderful project
